# Generated by Django 3.1.3 on 2020-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('sender_account_no', models.CharField(max_length=16)),
                ('rev_account_no', models.CharField(max_length=16)),
                ('rent_amount', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=11)),
            ],
        ),
    ]
