# Generated by Django 3.1.3 on 2020-11-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20201121_1831'),
        ('payments', '0003_rentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='month_of',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.propertyforrent'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='rent_paid',
            field=models.BooleanField(default=False),
        ),
    ]
