# Generated by Django 3.1.3 on 2020-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20201122_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='month_of',
            field=models.IntegerField(),
        ),
    ]
