# Generated by Django 3.1.1 on 2020-11-16 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20201116_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforrent',
            old_name='name',
            new_name='property_name',
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12)),
                ('acc_no', models.CharField(max_length=16)),
                ('property', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.propertyforrent')),
                ('property_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
