# Generated by Django 3.1.1 on 2020-11-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0004_auto_20201116_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='properties.propertyforrent'),
        ),
        migrations.DeleteModel(
            name='PropertyForRent',
        ),
    ]
