# Generated by Django 3.1.1 on 2020-11-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0005_auto_20201117_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.propertyforrent'),
        ),
    ]
