# Generated by Django 3.1.1 on 2020-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tenant_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
