# Generated by Django 3.1.3 on 2020-11-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201121_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='address_proof',
        ),
    ]
