# Generated by Django 3.1.3 on 2020-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_tenant_address_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address_proof',
            field=models.ImageField(default='default.jpg', upload_to='address_proofs/'),
        ),
    ]
