# Generated by Django 3.1.3 on 2020-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201121_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address_proof',
            field=models.ImageField(default='address_proofs/default.jpg', upload_to='address_proofs/'),
        ),
    ]
