# Generated by Django 3.1.3 on 2020-11-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201122_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='transaction_id',
        ),
    ]
