# Generated by Django 3.1.3 on 2020-11-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_buyers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyers',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterField(
            model_name='buyers',
            name='catagory',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Buyer', 'Buyer')], default='Buyer', max_length=20),
        ),
    ]
