# Generated by Django 3.1.1 on 2020-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ppty_owner',
            field=models.BooleanField(default=False),
        ),
    ]
