# Generated by Django 3.1.1 on 2020-11-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_ppty_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
