# Generated by Django 3.1.3 on 2021-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
