# Generated by Django 3.1.1 on 2020-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyforrent_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforrent',
            name='security_deposit',
            field=models.IntegerField(default=0),
        ),
    ]
