# Generated by Django 3.1.3 on 2020-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyforrent_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforrent',
            name='image1',
            field=models.ImageField(default='house.png', upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image2',
            field=models.ImageField(default='house.png', upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image3',
            field=models.ImageField(default='house.png', upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='image4',
            field=models.ImageField(default='house.png', upload_to='house_images/'),
        ),
    ]
