# Generated by Django 3.1.3 on 2020-11-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyforsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforsale',
            name='ceritification',
            field=models.CharField(choices=[('A', 'A-Khata'), ('B', 'B-Khata')], default='B-Khata', max_length=8),
        ),
    ]
