# Generated by Django 3.1.3 on 2020-11-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20201124_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyforsale',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties for Sale'},
        ),
    ]
