# Generated by Django 3.1.3 on 2020-11-26 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_appointment',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_appointement',
            field=models.DateField(),
        ),
    ]
