# Generated by Django 3.1.3 on 2020-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20201210_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyforsale',
            name='area',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='no',
        ),
        migrations.RemoveField(
            model_name='propertyforsale',
            name='state',
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='address',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
