# Generated by Django 3.1.3 on 2021-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20201216_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforrent',
            name='has_maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
